-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/shp_extensions.yaml
-- Datatype: reviews, Platform: shp
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_shp_reviews___raw (
  review_id VARCHAR NOT NULL CHECK (length(review_id) > 0),
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  rating DOUBLE NOT NULL CHECK (rating >= 0 AND rating <= 5),
  review_date VARCHAR NOT NULL CHECK (length(review_date) > 0),
  review_text VARCHAR,
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  shp_review_app VARCHAR,
  shp_verified_buyer BOOLEAN,
  shp_review_picture_urls VARCHAR
);
