-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/shp_extensions.yaml
-- Datatype: sales, Platform: shp
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_shp_sales___raw (
  order_id VARCHAR NOT NULL CHECK (length(order_id) > 0),
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  order_date VARCHAR NOT NULL CHECK (length(order_date) > 0),
  quantity INTEGER NOT NULL CHECK (quantity >= 1),
  unit_price DOUBLE NOT NULL CHECK (unit_price >= 0),
  total_amount DOUBLE NOT NULL CHECK (total_amount >= 0),
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  shp_shop_domain VARCHAR NOT NULL CHECK (shp_shop_domain ~ '^[a-z0-9-]+\.myshopify\.com$'),
  shp_order_number VARCHAR,
  shp_financial_status VARCHAR,
  shp_fulfillment_status VARCHAR,
  shp_currency VARCHAR NOT NULL CHECK (shp_currency ~ '^[A-Z]{3}$'),
  shp_landing_site VARCHAR,
  shp_referring_site VARCHAR,
  shp_source_name VARCHAR,
  shp_tags VARCHAR,
  shp_discount_codes VARCHAR
);
