-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/eby_extensions.yaml
-- Datatype: products, Platform: eby
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_eby_products___raw (
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  sku VARCHAR NOT NULL CHECK (length(sku) > 0),
  marketplace VARCHAR NOT NULL CHECK (marketplace ~ '^[a-z]{3}_[a-z]{2,3}$|^[a-z]{3}$' AND length(marketplace) > 0),
  product_line_id VARCHAR NOT NULL CHECK (length(product_line_id) > 0),
  product_name VARCHAR NOT NULL CHECK (length(product_name) > 0),
  brand VARCHAR NOT NULL CHECK (length(brand) > 0),
  is_own_product BOOLEAN NOT NULL,
  is_active BOOLEAN,
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  eby_item_id VARCHAR,
  eby_listing_type VARCHAR,
  eby_start_price DOUBLE,
  eby_buy_it_now_price DOUBLE,
  eby_condition VARCHAR,
  eby_condition_id INTEGER,
  eby_primary_category_id VARCHAR,
  eby_primary_category_name VARCHAR,
  eby_secondary_category_id VARCHAR,
  eby_store_category VARCHAR,
  eby_quantity_available INTEGER,
  eby_watchers INTEGER,
  eby_bids INTEGER,
  eby_listing_duration VARCHAR,
  eby_best_offer_enabled BOOLEAN
);
