-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Datatype: orders, Core-only
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_core_orders (
  order_id VARCHAR NOT NULL CHECK (length(order_id) > 0),
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  order_date VARCHAR NOT NULL CHECK (length(order_date) > 0),
  order_status VARCHAR NOT NULL CHECK (length(order_status) > 0),
  total_amount DOUBLE NOT NULL CHECK (total_amount >= 0),
  shipping_amount DOUBLE CHECK (shipping_amount >= 0),
  tax_amount DOUBLE CHECK (tax_amount >= 0),
  payment_method VARCHAR,
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0)
);
