-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/official_website_extensions.yaml
-- Datatype: sales, Platform: official_website
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_official_website_sales___raw (
  order_id VARCHAR NOT NULL CHECK (length(order_id) > 0),
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  order_date VARCHAR NOT NULL CHECK (length(order_date) > 0),
  quantity INTEGER NOT NULL CHECK (quantity >= 1),
  unit_price DOUBLE NOT NULL CHECK (unit_price >= 0),
  total_amount DOUBLE NOT NULL CHECK (total_amount >= 0),
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  ow_site_domain VARCHAR NOT NULL CHECK (ow_site_domain ~ '^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$'),
  ow_session_id VARCHAR,
  ow_user_agent VARCHAR,
  ow_referrer_url VARCHAR,
  ow_utm_source VARCHAR,
  ow_utm_medium VARCHAR,
  ow_utm_campaign VARCHAR,
  ow_utm_term VARCHAR,
  ow_utm_content VARCHAR,
  ow_landing_page VARCHAR,
  ow_payment_gateway VARCHAR,
  ow_currency VARCHAR CHECK ((ow_currency ~ '^[A-Z]{3}$' OR ow_currency = '')),
  ow_discount_code VARCHAR,
  ow_discount_amount DOUBLE
);
