-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/amz_extensions.yaml
-- Datatype: company_product_extension, Platform: amz
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_amz_company_product_extension___raw (
  sku VARCHAR NOT NULL CHECK (length(sku) > 0),
  marketplace VARCHAR NOT NULL,
  brand VARCHAR NOT NULL,
  amz_asin VARCHAR,
  product_line_id VARCHAR,
  product_name VARCHAR,
  cost_factory_price DOUBLE,
  cost_factory_price_estimated_23pct DOUBLE,
  fee_inbound_freight DOUBLE,
  fee_fba DOUBLE,
  fee_warehouse_rent DOUBLE,
  fee_amazon_commission DOUBLE,
  fee_amazon_commission_pct DOUBLE,
  fee_other DOUBLE,
  price_listing DOUBLE,
  price_msrp DOUBLE,
  net_profit DOUBLE,
  profit_margin_pct DOUBLE,
  status VARCHAR,
  launch_date DATE
);
