-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/amz_extensions.yaml
-- Datatype: customers, Platform: amz
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_amz_customers___raw (
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  customer_email VARCHAR CHECK ((customer_email ~ '^[^@]+@[^@]+\.[^@]+$' OR customer_email = '')),
  customer_name VARCHAR,
  registration_date VARCHAR,
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  amz_buyer_email VARCHAR,
  amz_buyer_county VARCHAR,
  amz_buyer_purchase_order_number VARCHAR,
  amz_buyer_tax_info VARCHAR
);
