-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/amz_extensions.yaml
-- Datatype: products, Platform: amz
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_amz_products___raw (
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  sku VARCHAR NOT NULL CHECK (length(sku) > 0),
  marketplace VARCHAR NOT NULL CHECK (marketplace ~ '^[a-z]{3}_[a-z]{2,3}$|^[a-z]{3}$' AND length(marketplace) > 0),
  product_line_id VARCHAR NOT NULL CHECK (length(product_line_id) > 0),
  product_name VARCHAR NOT NULL CHECK (length(product_name) > 0),
  brand VARCHAR NOT NULL CHECK (length(brand) > 0),
  is_own_product BOOLEAN NOT NULL,
  is_active BOOLEAN,
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  amz_asin VARCHAR NOT NULL CHECK (amz_asin ~ '^B0[A-Z0-9]{8}$|^[A-Z0-9]{10}$'),
  amz_parent_asin VARCHAR CHECK ((amz_parent_asin ~ '^B0[A-Z0-9]{8}$|^[A-Z0-9]{10}$' OR amz_parent_asin = '')),
  amz_browse_node_id VARCHAR,
  amz_listing_status VARCHAR,
  amz_buy_box_price DOUBLE,
  amz_brand_registry_id VARCHAR,
  amz_review_count INTEGER,
  amz_average_rating DOUBLE,
  amz_seller_sku VARCHAR,
  amz_marketplace_id VARCHAR
);
