-- Auto-generated by fn_generate_create_table_from_yaml.R
-- Source: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/core_schemas.yaml
-- Platform extension: /Users/che/Library/CloudStorage/Dropbox/che_workspace/projects/ai_martech/l4_enterprise/shared/global_scripts/01_db/raw_schema/_authoring/platform_extensions/amz_extensions.yaml
-- Datatype: sales, Platform: amz
-- Bound by MP102 (v1.2) per MP156 Two-Tier Normativity (issue #489)
-- DO NOT EDIT BY HAND. Edit the authoring yaml and re-run _build.R.

CREATE TABLE IF NOT EXISTS df_amz_sales___raw (
  order_id VARCHAR NOT NULL CHECK (length(order_id) > 0),
  customer_id VARCHAR NOT NULL CHECK (length(customer_id) > 0),
  product_id VARCHAR NOT NULL CHECK (product_id ~ '^[A-Za-z0-9._-]+$' AND length(product_id) > 0),
  order_date VARCHAR NOT NULL CHECK (length(order_date) > 0),
  quantity INTEGER NOT NULL CHECK (quantity >= 1),
  unit_price DOUBLE NOT NULL CHECK (unit_price >= 0),
  total_amount DOUBLE NOT NULL CHECK (total_amount >= 0),
  platform_id VARCHAR NOT NULL CHECK (platform_id ~ '^[a-z]{3}$|^official_website$' AND (length(platform_id) = 3 OR platform_id = 'official_website') AND lower(platform_id) = platform_id),
  import_timestamp TIMESTAMP NOT NULL,
  import_source VARCHAR NOT NULL CHECK (length(import_source) > 0),
  amz_marketplace_id VARCHAR NOT NULL CHECK (amz_marketplace_id ~ '^[A-Z0-9]+$'),
  amz_fulfillment_channel VARCHAR NOT NULL CHECK (amz_fulfillment_channel ~ '^(AFN|MFN)$'),
  amz_fba_status VARCHAR,
  amz_seller_sku VARCHAR,
  amz_amazon_order_id VARCHAR NOT NULL CHECK (amz_amazon_order_id ~ '^[0-9]{3}-[0-9]{7}-[0-9]{7}$'),
  amz_is_business_order BOOLEAN,
  amz_is_prime BOOLEAN,
  amz_promotion_ids VARCHAR,
  amz_shipping_service_level VARCHAR
);
